[package]

name = "rust_bignum_fuzzer"
version = "0.0.1"
authors = [ "Guido Vranken <guidovranken@gmail.com>" ]

[dependencies]
num = "0.1" 
lazy_static = "0.2"
ethcore-bigint = { path = "util/bigint", features = ["std"]}
